export const ROUTES = Object.freeze({
  CUSTOMERS: "/customers",
  ADDNEWCUSTOMER: "/AddNewcustomer",
  ADDNEWQUOTATION: "/AddNewQuotation",
  PRODUCTS: "/products",
  ADDSUPPLIER: "/addsupplier",
  VIEWCUSTOMER: "/viewcustomer",
  VIEWSUPPLIER: "/viewsupplier",
  CATEGORY: "/category",
  LAYOUT: "/layout",
  SUPPLIERS: "/suppliers",
  ADDPRODUCT: "/addproduct",
  VIEWPRODUCT: "/viewproduct",
  // ADDSUPPLIER:"/addsupplier",
  // VIEWCUSTOMER:"/viewcustomer",
  // VIEWSUPPLIER:"/viewsupplier",
  // CATEGORY:"/category",
  // LAYOUT:"/layout",
  // SUPPLIERS:"/suppliers",
  // DASHBOARD:"/dashboard"
});
